### ISSUE TITLE
comma inside card should be after the text and not as single comma in middle 

### ISSUE THREAD

**Issue by snehaajency** [ajency/Cibil-Dispute#54]
![Screenshot_2021-11-01-15-50-36-342_com android chrome](https://user-images.githubusercontent.com/4660706/139657323-174858b1-1a85-42e9-aa48-a24fe7179b8c.jpg)

**Comment by chaitanya-ajency** [comment]
![Capture](https://user-images.githubusercontent.com/79827708/139790932-ac498b14-018a-4db8-ad67-892f20a2871a.PNG)
