### ISSUE TITLE
can see a vertical line near delete option

### ISSUE THREAD

**Issue by snehaajency** [ajency/Cibil-Dispute#64]
![image](https://user-images.githubusercontent.com/4660706/139786517-7190daa9-9521-4b90-a004-556f7253fdf1.png)

**Comment by chaitanya-ajency** [comment]
![screenshot-127 0 0 1_5501-2021 11 02-10_56_22](https://user-images.githubusercontent.com/79827708/139791305-05ba9cd6-0921-432f-a9e0-d85dc6fbf0d7.png)

**Comment by snehaajency** [comment]
@chaitanya-ajency could replicate on 3 devices + emulator
