### ISSUE TITLE
text overlapping the icon,also check font family 

### ISSUE THREAD

**Issue by snehaajency** [ajency/Cibil-Dispute#94]
![image](https://user-images.githubusercontent.com/4660706/139844640-c5dcafd8-e584-4851-b323-083576e9102a.png)

**Comment by snehaajency** [comment]
@chaitanya-ajency font family is intro book indesign

**Comment by ankitasangodkar** [comment]
This is same as : https://ajency.github.io/Cibil-Dispute/NON-GCVD/dispute-landing-page.html
